# 1. Write a Python Program to Add Two Matrices?

In [7]:
import numpy as np

def matrix_add(matrix1 , matrix2):
    sum = np.add(matrix1 , matrix2)
    return sum

matrix1 = np.array([[4,6,7],[7,5,9],[4,9,6]])
matrix2 = np.array([[2,4,6],[9,1,7],[3,8,5]])

result = matrix_add(matrix1,matrix2)

print(f'First matrix : \n{matrix1}\n')

print(f'Second matrix : \n{matrix2}\n')

print(f'Sum of both matrix : \n{result}')


First matrix : 
[[4 6 7]
 [7 5 9]
 [4 9 6]]

Second matrix : 
[[2 4 6]
 [9 1 7]
 [3 8 5]]

Sum of both matrix : 
[[ 6 10 13]
 [16  6 16]
 [ 7 17 11]]


# 2. Write a Python Program to Multiply Two Matrices?

In [9]:
import numpy as np

def matrix_mul(matrix1 , matrix2):
    mul = np.matmul(matrix1 , matrix2)
    return mul

matrix1 = np.array([[4,6,7],[7,5,9],[4,9,6]])
matrix2 = np.array([[2,4,6],[9,1,7],[3,8,5]])

result = matrix_mul(matrix1,matrix2)

print(f'First matrix : \n{matrix1}\n')

print(f'Second matrix : \n{matrix2}\n')

print(f'Multiplication of both matrix : \n{result}')

First matrix : 
[[4 6 7]
 [7 5 9]
 [4 9 6]]

Second matrix : 
[[2 4 6]
 [9 1 7]
 [3 8 5]]

Multiplication of both matrix : 
[[ 83  78 101]
 [ 86 105 122]
 [107  73 117]]


# 3. Write a Python Program to Transpose a Matrix?

In [11]:
import numpy as np

def matrix_trs(matrix):
    tp = np.transpose(matrix)
    return tp

matrix = np.array([[4,6,7],[7,5,9],[4,9,6]])
result = matrix_trs(matrix)

print(f'Matrix is \n{matrix}\n')
print(f'Transpose of matrix is : \n{result}')

Matrix is 
[[4 6 7]
 [7 5 9]
 [4 9 6]]

Transpose of matrix is : 
[[4 7 4]
 [6 5 9]
 [7 9 6]]


# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [17]:
def sort(string):
    a = string.split()
    a.sort()
    for i in a:
        print(i)

my_str = input("Enter a string: ")

sort(my_str)


Enter a string: may the force be with you
be
force
may
the
with
you


# 5. Write a Python Program to Remove Punctuation From a String?

In [21]:
def remove_pnc(string):
    Punctuation = '''''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    no_Punctuation = ""
    for i in string:
        if i not in Punctuation:
            no_Punctuation += i
    return no_Punctuation

my_str = input("Enter a string: ")

my_str_without_punctuation = remove_pnc(my_str)
print(my_str_without_punctuation)


Enter a string: may!!!!!,,,,,, the force be with you.................
may the force be with you
